### ISSUE TITLE
["bug"] Number of days to project is not correct

### ISSUE THREAD

**Issue by mdbecker** [CodeForPhilly/chime#350]
## Description:
The SIR model is run for `Number of days since first admin` + `Number of days to project` days but because of the LOS parameters the census only projects out by `Number of days since first admin` + `Number of days to project` - `max(LOS)` (where the max LOS defaults to 10). This results in the graphs not actually projecting the full `Number of days to project`. To address this, the SIR model should be run for `Number of days since first admin` + `Number of days to project` + `max(LOS)` and then the DataFrame returned by `build_census_df` and `build_admits_df` should only return the first ``Number of days since first admin` + `Number of days to project` values (i.e. `.head()`)

### Expected behavior:
The admissions and census DataFrames should project exactly `Number of days since first admin` + `Number of days to project` days. Add a test case to the test suite to ensure this is the case. Make sure the test case fails before you implement a fix.

### What I got instead:
![image](https://user-images.githubusercontent.com/1069047/77859487-c8439100-71d7-11ea-976c-a7bf7bc7d0dc.png)

**Comment by jlubken** [comment]
This has been fixed mostly. The fitting function uses the n_days to project to attempt to fit. This will fail if the curve hasn't advanced enough to match the number of hospitalized.

Once fit, the sim re-runs with full span of (-i_day, n_days) and projects the full n_days into the future.

**Comment by PhilMiller** [comment]
Fixed by https://github.com/CodeForPhilly/chime/pull/365/ - the projection is already run long enough, the forecast computation just mistakenly truncated it be LOS

**Comment by PhilMiller** [comment]
Or, at least partially fixed - there may be some difference of additional days that should be getting forecast and aren't.
